# Generated by Django 5.2.15 on 2026-06-13 23:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("core", "0001_initial"),
        ("geo", "0001_initial"),
        ("program", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimensions",
                        to="core.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("project", "code")},
            },
        ),
        migrations.CreateModel(
            name="DimensionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="indicators.dimension",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("dimension", "code")},
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=500)),
                ("definition", models.TextField(blank=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("NUMBER", "Nombre"),
                            ("PERCENTAGE", "Pourcentage"),
                            ("CURRENCY", "Monétaire"),
                            ("RATIO", "Ratio"),
                            ("TEXT", "Texte"),
                        ],
                        default="NUMBER",
                        max_length=16,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("INCREASE", "Croissant"),
                            ("DECREASE", "Décroissant"),
                        ],
                        default="INCREASE",
                        max_length=16,
                    ),
                ),
                (
                    "aggregation_method",
                    models.CharField(
                        choices=[
                            ("SUM", "Somme"),
                            ("AVERAGE", "Moyenne"),
                            ("LAST", "Dernière valeur"),
                            ("MAX", "Maximum"),
                            ("MIN", "Minimum"),
                            ("MANUAL", "Manuel"),
                        ],
                        default="SUM",
                        max_length=16,
                    ),
                ),
                ("is_cri", models.BooleanField(default=False)),
                (
                    "reporting_frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Mensuel"),
                            ("QUARTERLY", "Trimestriel"),
                            ("SEMESTERLY", "Semestriel"),
                            ("ANNUAL", "Annuel"),
                            ("ADHOC", "Ponctuel"),
                        ],
                        default="QUARTERLY",
                        max_length=16,
                    ),
                ),
                ("data_source", models.CharField(blank=True, max_length=500)),
                ("collection_tool", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indicators",
                        to="program.programnode",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="core.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalMeasurement",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SUBMITTED", "Soumis"),
                            ("VALIDATED", "Validé"),
                            ("AUDITED", "Audité"),
                            ("CONSOLIDATED", "Consolidé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("period_year", models.PositiveIntegerField()),
                (
                    "period_quarter",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "period_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("period_date", models.DateField(blank=True, null=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Saisie manuelle"),
                            ("IMPORT", "Import"),
                            ("SURVEY", "Enquête"),
                        ],
                        default="MANUAL",
                        max_length=16,
                    ),
                ),
                ("narrative", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geo_unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="geo.geounit",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program_node",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="program.programnode",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="indicators.indicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical measurement",
                "verbose_name_plural": "historical measurements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="IndicatorDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicators.dimension",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="indicators.indicator",
                    ),
                ),
            ],
            options={
                "unique_together": {("indicator", "dimension")},
            },
        ),
        migrations.AddField(
            model_name="indicator",
            name="dimensions",
            field=models.ManyToManyField(
                blank=True,
                related_name="indicators",
                through="indicators.IndicatorDimension",
                to="indicators.dimension",
            ),
        ),
        migrations.CreateModel(
            name="IndicatorResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responsibility",
                    models.CharField(
                        choices=[
                            ("COLLECTION", "Collecte"),
                            ("VALIDATION", "Validation"),
                            ("AUDIT", "Audit/Contrôle"),
                            ("TRANSFER_MIS", "Transfert vers le MIS"),
                            ("AGGREGATION", "Agrégation"),
                            ("ANALYSIS", "Analyse"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibilities",
                        to="indicators.indicator",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.role",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IndicatorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_types",
                        to="core.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("project", "code")},
            },
        ),
        migrations.AddField(
            model_name="indicator",
            name="indicator_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="indicators",
                to="indicators.indicatortype",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalIndicator",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=500)),
                ("definition", models.TextField(blank=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("NUMBER", "Nombre"),
                            ("PERCENTAGE", "Pourcentage"),
                            ("CURRENCY", "Monétaire"),
                            ("RATIO", "Ratio"),
                            ("TEXT", "Texte"),
                        ],
                        default="NUMBER",
                        max_length=16,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("INCREASE", "Croissant"),
                            ("DECREASE", "Décroissant"),
                        ],
                        default="INCREASE",
                        max_length=16,
                    ),
                ),
                (
                    "aggregation_method",
                    models.CharField(
                        choices=[
                            ("SUM", "Somme"),
                            ("AVERAGE", "Moyenne"),
                            ("LAST", "Dernière valeur"),
                            ("MAX", "Maximum"),
                            ("MIN", "Minimum"),
                            ("MANUAL", "Manuel"),
                        ],
                        default="SUM",
                        max_length=16,
                    ),
                ),
                ("is_cri", models.BooleanField(default=False)),
                (
                    "reporting_frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Mensuel"),
                            ("QUARTERLY", "Trimestriel"),
                            ("SEMESTERLY", "Semestriel"),
                            ("ANNUAL", "Annuel"),
                            ("ADHOC", "Ponctuel"),
                        ],
                        default="QUARTERLY",
                        max_length=16,
                    ),
                ),
                ("data_source", models.CharField(blank=True, max_length=500)),
                ("collection_tool", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program_node",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="program.programnode",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indicator_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="indicators.indicatortype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical indicator",
                "verbose_name_plural": "historical indicators",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SUBMITTED", "Soumis"),
                            ("VALIDATED", "Validé"),
                            ("AUDITED", "Audité"),
                            ("CONSOLIDATED", "Consolidé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("period_year", models.PositiveIntegerField()),
                (
                    "period_quarter",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "period_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("period_date", models.DateField(blank=True, null=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Saisie manuelle"),
                            ("IMPORT", "Import"),
                            ("SURVEY", "Enquête"),
                        ],
                        default="MANUAL",
                        max_length=16,
                    ),
                ),
                ("narrative", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geo_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="measurements",
                        to="geo.geounit",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurements",
                        to="indicators.indicator",
                    ),
                ),
                (
                    "program_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="program.programnode",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="core.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeasurementValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "dimension_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="indicators.dimensioncategory",
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_values",
                        to="indicators.measurement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndicatorTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=18)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geo_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="geo.geounit",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="indicators.indicator",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="core.milestone",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("indicator", "milestone", "geo_unit")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="indicator",
            unique_together={("project", "code")},
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["indicator", "period_year", "period_quarter"],
                name="indicators__indicat_51087c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["geo_unit"], name="indicators__geo_uni_72a2ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(fields=["status"], name="indicators__status_79376d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="measurementvalue",
            unique_together={("measurement", "dimension_category")},
        ),
    ]
