# Generated by Django 5.2.17 on 2026-08-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programnode',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='programnode',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='programnode',
            name='node_type',
            field=models.CharField(choices=[('COMPONENT', 'Composante'), ('SUBCOMPONENT', 'Sous-composante')], default='COMPONENT', max_length=16),
        ),
    ]
