# Generated by Django 5.2.15 on 2026-06-13 23:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("geo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrievanceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("sla_days", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievance_types",
                        to="core.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("project", "code")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalGrievance",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SUBMITTED", "Soumis"),
                            ("VALIDATED", "Validé"),
                            ("AUDITED", "Audité"),
                            ("CONSOLIDATED", "Consolidé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local"),
                            ("REGIONAL", "Régional"),
                            ("NATIONAL", "National"),
                            ("OTHER", "Autre"),
                        ],
                        default="LOCAL",
                        max_length=16,
                    ),
                ),
                ("channel", models.CharField(blank=True, max_length=120)),
                ("summary", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("complainant_name", models.CharField(blank=True, max_length=255)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("received_at", models.DateField()),
                ("resolved_at", models.DateField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Reçue"),
                            ("IN_PROGRESS", "En cours"),
                            ("RESOLVED", "Résolue"),
                            ("CLOSED", "Clôturée"),
                            ("REJECTED", "Rejetée"),
                        ],
                        default="RECEIVED",
                        max_length=16,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geo_unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="geo.geounit",
                    ),
                ),
                (
                    "grievance_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="grievances.grievancetype",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical grievance",
                "verbose_name_plural": "historical grievances",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Grievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SUBMITTED", "Soumis"),
                            ("VALIDATED", "Validé"),
                            ("AUDITED", "Audité"),
                            ("CONSOLIDATED", "Consolidé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local"),
                            ("REGIONAL", "Régional"),
                            ("NATIONAL", "National"),
                            ("OTHER", "Autre"),
                        ],
                        default="LOCAL",
                        max_length=16,
                    ),
                ),
                ("channel", models.CharField(blank=True, max_length=120)),
                ("summary", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("complainant_name", models.CharField(blank=True, max_length=255)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("received_at", models.DateField()),
                ("resolved_at", models.DateField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Reçue"),
                            ("IN_PROGRESS", "En cours"),
                            ("RESOLVED", "Résolue"),
                            ("CLOSED", "Clôturée"),
                            ("REJECTED", "Rejetée"),
                        ],
                        default="RECEIVED",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geo_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="geo.geounit",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievances",
                        to="core.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grievance_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grievances",
                        to="grievances.grievancetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "state"],
                        name="grievances__project_34c768_idx",
                    ),
                    models.Index(
                        fields=["status"], name="grievances__status_6af4cf_idx"
                    ),
                ],
            },
        ),
    ]
