# Generated by Django 5.2.17 on 2026-09-26 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_actor_auditlog_partner_unitofmeasure'),
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kobo_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('kobo_uuid', models.CharField(db_index=True, max_length=255)),
                ('kobo_submission_time', models.DateTimeField(blank=True, null=True)),
                ('kobo_submitted_by', models.CharField(blank=True, max_length=255)),
                ('kobo_wilaya', models.CharField(blank=True, max_length=255)),
                ('kobo_moughataa', models.CharField(blank=True, max_length=255)),
                ('kobo_commune', models.CharField(blank=True, max_length=255)),
                ('village_locality', models.CharField(blank=True, max_length=255)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_altitude', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('enumerator_name', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('infrastructure_type', models.CharField(blank=True, max_length=100)),
                ('infrastructure_type_other', models.CharField(blank=True, max_length=255)),
                ('has_rehabilitation', models.BooleanField(default=False)),
                ('has_maintenance', models.BooleanField(default=False)),
                ('has_governance', models.BooleanField(default=False)),
                ('intervention_type', models.CharField(blank=True, max_length=100)),
                ('intervention_type_other', models.CharField(blank=True, max_length=255)),
                ('works_completed', models.BooleanField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('rehab_functional', models.BooleanField(blank=True, null=True)),
                ('management_structure_exists', models.BooleanField(blank=True, null=True)),
                ('management_structure_name', models.CharField(blank=True, max_length=500)),
                ('maintenance_functional', models.BooleanField(blank=True, null=True)),
                ('maintenance_last_12_months', models.BooleanField(blank=True, null=True)),
                ('committee_name', models.CharField(blank=True, max_length=500)),
                ('committee_functional', models.BooleanField(blank=True, null=True)),
                ('committee_has_women', models.BooleanField(blank=True, null=True)),
                ('committee_members_total', models.PositiveIntegerField(blank=True, null=True)),
                ('committee_women_total', models.PositiveIntegerField(blank=True, null=True)),
                ('women_functions', models.JSONField(blank=True, default=list)),
                ('women_functions_other', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('geo_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructures', to='geo.geounit')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-kobo_submission_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_type', models.CharField(blank=True, max_length=100)),
                ('maintenance_type_other', models.CharField(blank=True, max_length=500)),
                ('kobo_uuid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='infrastructure.infrastructure')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-maintenance_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructurePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='infrastructure/photos/%Y/%m/')),
                ('kobo_filename', models.CharField(blank=True, max_length=500)),
                ('kobo_url', models.TextField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='infrastructure.infrastructure')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='infrastructure/videos/%Y/%m/')),
                ('kobo_filename', models.CharField(blank=True, max_length=500)),
                ('kobo_url', models.TextField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='infrastructure.infrastructure')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='infrastructure',
            index=models.Index(fields=['project', 'kobo_uuid'], name='infrastruct_project_38aabd_idx'),
        ),
        migrations.AddIndex(
            model_name='infrastructure',
            index=models.Index(fields=['geo_unit'], name='infrastruct_geo_uni_6e48b9_idx'),
        ),
        migrations.AddIndex(
            model_name='infrastructure',
            index=models.Index(fields=['infrastructure_type'], name='infrastruct_infrast_a1a46f_idx'),
        ),
        migrations.AddConstraint(
            model_name='infrastructure',
            constraint=models.UniqueConstraint(fields=('project', 'kobo_uuid'), name='unique_infrastructure_kobo_uuid_project'),
        ),
        migrations.AddIndex(
            model_name='infrastructuremaintenance',
            index=models.Index(fields=['project', 'infrastructure'], name='infrastruct_project_089848_idx'),
        ),
    ]
