// Metabase dashboard ids (baked at build per 06_dashboards_metabase.md §6.5).
export const MB = {
  RESULTS_PHYSICAL: import.meta.env.VITE_MB_DASHBOARD_RESULTS_PHYSICAL,
  RESULTS_FRAMEWORK: import.meta.env.VITE_MB_DASHBOARD_RESULTS_FRAMEWORK,
  FINANCE_CATEGORY: import.meta.env.VITE_MB_DASHBOARD_FINANCE_CATEGORY,
  FINANCE_COMPONENT: import.meta.env.VITE_MB_DASHBOARD_FINANCE_COMPONENT,
  PROCUREMENT: import.meta.env.VITE_MB_DASHBOARD_PROCUREMENT,
  GRIEVANCES: import.meta.env.VITE_MB_DASHBOARD_GRIEVANCES,
  IMPACT: import.meta.env.VITE_MB_DASHBOARD_IMPACT,
  ACTIVITIES: import.meta.env.VITE_MB_DASHBOARD_ACTIVITIES,
};
