# Generated by Django 5.2.15 on 2026-06-13 23:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("origin", models.CharField(blank=True, max_length=255)),
                ("organization", models.CharField(blank=True, max_length=255)),
                ("function", models.CharField(blank=True, max_length=255)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Homme"), ("F", "Femme")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalActivity",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SUBMITTED", "Soumis"),
                            ("VALIDATED", "Validé"),
                            ("AUDITED", "Audité"),
                            ("CONSOLIDATED", "Consolidé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TRAINING", "Formation"),
                            ("AWARENESS", "Sensibilisation"),
                            ("FIELD_VISIT", "Visite de terrain"),
                            ("VISIT_RECEIVED", "Visite reçue"),
                            ("MEETING", "Réunion"),
                            ("SUBPROJECT", "Sous-projet"),
                            ("STAKEHOLDER", "Autre intervenant"),
                            ("OBSERVATION", "Changement observé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("organizer", models.CharField(blank=True, max_length=255)),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("objective", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "total_participants",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("women_count", models.PositiveIntegerField(blank=True, null=True)),
                ("youth_count", models.PositiveIntegerField(blank=True, null=True)),
                ("submission_date", models.DateField(blank=True, null=True)),
                (
                    "funding_requested",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "funding_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("funding_date", models.DateField(blank=True, null=True)),
                ("management_committee", models.CharField(blank=True, max_length=500)),
                ("beneficiary_org", models.CharField(blank=True, max_length=500)),
                ("actor_name", models.CharField(blank=True, max_length=255)),
                ("implantation_date", models.DateField(blank=True, null=True)),
                ("main_actions", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical activity",
                "verbose_name_plural": "historical activitys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SUBMITTED", "Soumis"),
                            ("VALIDATED", "Validé"),
                            ("AUDITED", "Audité"),
                            ("CONSOLIDATED", "Consolidé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TRAINING", "Formation"),
                            ("AWARENESS", "Sensibilisation"),
                            ("FIELD_VISIT", "Visite de terrain"),
                            ("VISIT_RECEIVED", "Visite reçue"),
                            ("MEETING", "Réunion"),
                            ("SUBPROJECT", "Sous-projet"),
                            ("STAKEHOLDER", "Autre intervenant"),
                            ("OBSERVATION", "Changement observé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("organizer", models.CharField(blank=True, max_length=255)),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("objective", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "total_participants",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("women_count", models.PositiveIntegerField(blank=True, null=True)),
                ("youth_count", models.PositiveIntegerField(blank=True, null=True)),
                ("submission_date", models.DateField(blank=True, null=True)),
                (
                    "funding_requested",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "funding_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("funding_date", models.DateField(blank=True, null=True)),
                ("management_committee", models.CharField(blank=True, max_length=500)),
                ("beneficiary_org", models.CharField(blank=True, max_length=500)),
                ("actor_name", models.CharField(blank=True, max_length=255)),
                ("implantation_date", models.DateField(blank=True, null=True)),
                ("main_actions", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
