# Generated by Django 5.2.17 on 2026-08-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('implementation_modality', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['workplan__year', 'activity__code'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('is_planned', models.BooleanField(default=True)),
                ('planned_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['technical_plan', 'month'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('version', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['code']},
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='activities__project_1d1dd7_idx',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='activities__status_b1bb4f_idx',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='actor_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='beneficiary_org',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='funding_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='funding_obtained',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='funding_requested',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='implantation_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='main_actions',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='management_committee',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='total_participants',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='women_count',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='youth_count',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='actor_name',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='beneficiary_org',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='funding_date',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='funding_obtained',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='funding_requested',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='implantation_date',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='main_actions',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='management_committee',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='total_participants',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='women_count',
        ),
        migrations.RemoveField(
            model_name='historicalactivity',
            name='youth_count',
        ),
        migrations.AddField(
            model_name='activity',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
