# Generated by Django 5.2.17 on 2026-08-19 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_technicalplan_technicalschedule_workplan_and_more'),
        ('core', '0002_actor_auditlog_partner_unitofmeasure'),
        ('geo', '0001_initial'),
        ('indicators', '0001_initial'),
        ('program', '0002_remove_programnode_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.partner'),
        ),
        migrations.AddField(
            model_name='activity',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='responsible',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.partner'),
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='indicators.indicator'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='program_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='program.programnode'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['project', 'code'], name='activities__project_deb4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['program_node'], name='activities__program_d09460_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['responsible'], name='activities__respons_5930ae_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['indicator'], name='activities__indicat_a7bdd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_activity_code_per_project'),
        ),
        migrations.AddField(
            model_name='technicalplan',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_plans', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='technicalplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalplan',
            name='geo_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_plans', to='geo.geounit'),
        ),
        migrations.AddField(
            model_name='technicalplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_plans', to='core.project'),
        ),
        migrations.AddField(
            model_name='technicalplan',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_plans', to='core.partner'),
        ),
        migrations.AddField(
            model_name='technicalplan',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_plans', to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='technicalplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalschedule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_schedules', to='core.project'),
        ),
        migrations.AddField(
            model_name='technicalschedule',
            name='technical_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='activities.technicalplan'),
        ),
        migrations.AddField(
            model_name='technicalschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplans', to='core.project'),
        ),
        migrations.AddField(
            model_name='workplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalplan',
            name='workplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_plans', to='activities.workplan'),
        ),
        migrations.AddIndex(
            model_name='technicalschedule',
            index=models.Index(fields=['project', 'technical_plan'], name='activities__project_be32f0_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalschedule',
            index=models.Index(fields=['month'], name='activities__month_fd6495_idx'),
        ),
        migrations.AddConstraint(
            model_name='technicalschedule',
            constraint=models.UniqueConstraint(fields=('technical_plan', 'month'), name='unique_month_per_technical_plan'),
        ),
        migrations.AddIndex(
            model_name='workplan',
            index=models.Index(fields=['project', 'year'], name='activities__project_e39101_idx'),
        ),
        migrations.AddIndex(
            model_name='workplan',
            index=models.Index(fields=['is_current'], name='activities__is_curr_82f3fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='workplan',
            constraint=models.UniqueConstraint(fields=('project', 'year', 'version'), name='unique_workplan_project_year_version'),
        ),
        migrations.AddIndex(
            model_name='technicalplan',
            index=models.Index(fields=['project', 'workplan'], name='activities__project_185bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalplan',
            index=models.Index(fields=['activity'], name='activities__activit_4cf9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalplan',
            index=models.Index(fields=['geo_unit'], name='activities__geo_uni_13d59d_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalplan',
            index=models.Index(fields=['responsible'], name='activities__respons_f2e689_idx'),
        ),
        migrations.AddConstraint(
            model_name='technicalplan',
            constraint=models.UniqueConstraint(fields=('workplan', 'activity'), name='unique_activity_per_workplan'),
        ),
    ]
